import { Header, MenuMobile } from "@/components/sections";

import "@fontsource-variable/open-sans";
import "./globals.css";

export const runtime = "nodejs";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<div className="drawer">
					<input type="checkbox" id="menu" className="drawer-toggle" />
					<div className="drawer-content flex flex-col">
						<Header />
						<main className="-mt-20">{children}</main>
					</div>
					<MenuMobile />
				</div>
			</body>
		</html>
	);
}
