import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Header, MenuMobile } from "@/components/sections";

import "@fontsource-variable/open-sans";
import "./globals.css";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default async function RootLayout({
	children,
	params: { locale },
}: {
	children: React.ReactNode;
	params: { locale: string };
}) {
	const messages = await getMessages();

	return (
		<html lang={locale}>
			<body>
				<NextIntlClientProvider messages={messages}>
					<div className="drawer">
						<input type="checkbox" id="menu" className="drawer-toggle" />
						<div className="drawer-content flex flex-col">
							<Header />
							<main className="-mt-20">{children}</main>
						</div>
						<MenuMobile />
					</div>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
